export const LightingEffectsPolicy = {
  galaxy: {
    programmable: true,
    effectCount: 15,
    effects: [
      'ستاره‌های چشمک‌زن',
      'شهاب',
      'بارش شهاب',
      'موج نور',
      'نفس کهکشانی',
      'انفجار مرکزی',
      'مارپیچ کهکشانی',
      'حرکت رفت و برگشت',
      'پالس مرکز به بیرون',
      'پالس بیرون به مرکز',
      'دنباله ستاره',
      'سوسوی تصادفی نرم',
      'ابر نور آرام',
      'کهکشان زنده',
      'ترکیبی سینمایی',
    ],
    controls: ['speed', 'intensity', 'effect'],
  },
  outerNeon: {
    programmable: true,
    effectCount: 10,
    effects: [
      'تنفس نرم',
      'موج دورانی',
      'حرکت رفت و برگشت',
      'پالس ضربان',
      'دنباله نور',
      'پر شدن تدریجی',
      'خالی شدن تدریجی',
      'فلش سینمایی',
      'تعویض رنگ نرم',
      'حالت لوکس ترکیبی',
    ],
    controls: ['speed', 'intensity', 'effect'],
  },
  separateEngines: true,
};
